# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

#Added 
variables:
  solution: '**/*sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud/petTracker'
    organization: 'qaisqaisi'
    scannerMode: 'MSBuild'
    projectKey: 'qaisqaisi_PetTracker-P2'
    projectName: 'PetTracker-P2'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# #Added
# - task: UseDotNet@2
#   displayName: 'Use .Net Core sdk'
#   inputs:
#     packageType: runtime
#     version: 5.0.x



#Added
- task: VSTest@2
  displayName: 'Server Unit Test'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\XTest*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
 
- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
